# Site wide configuration

title: UFV Physics Student Association
locale: en_US
description: Providing community, support, and a voice for the physics and engineering students, and physics enthusiasts at the University of the Fraser Valley.
logo: psalogoinverted.png
search: true
url: 

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true
future: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Ryan Chowdhry
  association: PSA
  avatar: bio-photo.jpg
  email: ufv.physics@gmail.com
  disqus-shortname:
  twitter: ufvpsa
  facebook: ufvpsa
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: ufvpsa
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify: IMwoSfs3gcC9sbRLBzFAW74DEmWG5RuZJga7ypCTpdY
    ad-client:
    ad-slot:
  bing-verify:
